apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uf0b2ug1i-java-quarkus
  janus-idp.io/tekton: uf0b2ug1i-java-quarkus
  backstage.io/kubernetes-id: uf0b2ug1i-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uf0b2ug1i-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
